[dr]
type = drive
scope = drive
token = {"access_token":"YOUR_RCLONE_GDRIVE_TOKEN","token_type":"Bearer","refresh_token":"YOUR_RCLONE_REFRESH_TOKEN","expiry":"2024-07-11T06:39:14.134302658+07:00"}
root_folder_id = 0AHbW3-vl6Vn-Uk9PVA

